version: "3.8"
services:
  app:
    build: .
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./scripts/start.sh:/app/start.sh
      - ./.env:/app/.env
    command: ["sh", "/app/start.sh"]
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mounts init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
